const categoryUseCases: Record<string, string> = {
  Animals: 'display random animal facts and images in a pet or nature app',
  Anime: 'build an anime discovery or tracking feature',
  'Anti-Malware': 'scan user-submitted URLs or files for threats before processing',
  'Art & Design': 'enrich a creative platform with artwork, icons, or color palettes',
  'Authentication & Authorization': 'add secure, passwordless login to your application',
  Blockchain: 'query on-chain data or build a crypto dashboard',
  Books: 'build a reading list feature with book metadata and covers',
  'Business': 'automate business data lookups like company info or VAT validation',
  Calendar: 'integrate public holiday or event data into a scheduling app',
  'Cloud Storage & File Sharing': 'let users upload and manage files from within your app',
  'Continuous Integration': 'display live build status and CI metrics in your dev dashboard',
  Cryptocurrency: 'show live crypto prices and market data in a finance app',
  'Currency Exchange': 'convert prices between currencies in real time',
  'Data Validation': 'validate user input like emails, phone numbers, or addresses',
  'Development': 'generate placeholder data, test utilities, or mock APIs during development',
  Dictionaries: 'show word definitions, synonyms, and etymology on hover or click',
  Documents: 'parse and extract data from uploaded documents automatically',
  Email: 'validate email addresses or send transactional emails from your app',
  Entertainment: 'surface fun trivia, quotes, or random facts to delight users',
  Environment: 'display real-time air quality or environmental data in a geo app',
  Events: 'fetch and display local or global events on a discovery platform',
  Finance: 'show stock prices, financial statements, or portfolio data',
  'Food & Drink': 'suggest recipes or nutritional info based on user ingredients',
  Games: 'display game stats, items, or leaderboards in a gaming companion app',
  Geocoding: 'convert addresses to coordinates for mapping features',
  Government: 'surface public data like legislation, spending, or census info',
  Health: 'provide medical reference data or health metrics to users',
  Jobs: 'aggregate job listings from multiple sources in a career platform',
  Machine_Learning: 'add AI inference or model API calls to a feature',
  Music: 'show track metadata, lyrics, or recommendations in a music app',
  'News & Information': 'pull live headlines into a news feed or notification system',
  'Open Data': 'power data-driven dashboards with open government or research datasets',
  'Open Source Projects': 'show project stats or README badges in a developer portfolio',
  'Patent': 'search and display patent data for an IP research tool',
  Personality: 'add a fun personality quiz or horoscope feature to your app',
  Phone: 'validate and format phone numbers at sign-up',
  Photography: 'let users search and embed high-quality stock photos',
  Science: 'display scientific data, space imagery, or research findings',
  Security: 'check user credentials against breach databases during sign-up',
  Shopping: 'compare product prices across retailers in a deal-finding app',
  Social: 'aggregate social media stats or let users share content',
  Sports: 'show live scores, standings, or player stats in a sports app',
  Test: 'generate realistic test data for automated test suites',
  'Text Analysis': 'analyze sentiment or extract keywords from user content',
  Tracking: 'track shipments or deliveries in real time',
  Transportation: 'show flight or transit schedules in a travel planning app',
  URL_Shorteners: 'shorten links shared by users and track click analytics',
  'Vehicle': 'look up vehicle registration or VIN data for an automotive app',
  Video: 'embed video search or metadata in a media platform',
  Weather: 'show current conditions and forecasts in a location-aware app',
};

export function generateUseCase(category: string, name: string, description: string): string {
  const base = categoryUseCases[category];
  if (base) return base;
  return `integrate ${name.toLowerCase()} to ${description.toLowerCase().replace(/\.$/, '')} in your app`;
}
